/******************************************************************************
 *  plate-tectonics, a plate tectonics simulation library
 *  Copyright (C) 2012-2013 Lauri Viitanen
 *  Copyright (C) 2014-2015 Federico Tomassetti, Bret Curtis
 *
 *  This library is free software; you can redistribute it and/or
 *  modify it under the terms of the GNU Lesser General Public
 *  License as published by the Free Software Foundation; either
 *  version 2.1 of the License, or (at your option) any later version.
 *
 *  This library is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *  Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public
 *  License along with this library; if not, see http://www.gnu.org/licenses/
 *****************************************************************************/

#include "platecapi.hpp"
#include "map_drawing.hpp"
#include "sqrdmd.hpp"
#include "gtest/gtest.h"
#include <cstdlib>
#include <cstring>
#include <fstream>
#include <vector>

///
/// Regression test to ensure simulation output remains consistent
/// Uses seed 12345 and compares file checksums of generated images
///

namespace {

// Simple CRC32 implementation (no external dependencies)
uint32_t crc32(const unsigned char* data, size_t length) {
    uint32_t crc = 0xFFFFFFFF;
    for (size_t i = 0; i < length; i++) {
        crc ^= data[i];
        for (int j = 0; j < 8; j++) {
            crc = (crc >> 1) ^ (0xEDB88320 & -(crc & 1));
        }
    }
    return ~crc;
}

// Helper function to compute CRC32 checksum of a file
uint32_t compute_file_checksum(const char* filename) {
    std::ifstream file(filename, std::ios::binary);
    if (!file) {
        return 0;
    }

    // Read entire file into memory
    file.seekg(0, std::ios::end);
    size_t size = file.tellg();
    file.seekg(0, std::ios::beg);

    std::vector<unsigned char> buffer(size);
    file.read(reinterpret_cast<char*>(buffer.data()), size);

    return crc32(buffer.data(), size);
}

// Helper functions from simulation.cpp
void produce_image_colors(float* heightmap, int width, int height, const char* filename) {
    writeImageColors((char*)filename, width, height, heightmap, "FOO");
}

void save_image(void* p, const char* filename, const int width, const int height) {
    const float* heightmap = platec_api_get_heightmap(p);
    float* copy = new float[width * height];
    memcpy(copy, heightmap, sizeof(float) * width * height);
    normalize(copy, width * height);
    produce_image_colors(copy, width, height, filename);
    delete[] copy;
}

} // anonymous namespace

TEST(Regression, SimulationSeed12345_OutputConsistency) {
    // Expected CRC32 checksums from baseline run with seed 12345
    // Generated by: ./build/examples/simulation -s 12345 --filename /tmp/baseline
    const uint32_t EXPECTED_INITIAL_CRC32 = 0x0E3AFF64;
    const uint32_t EXPECTED_FINAL_CRC32 = 0x82FA4F0B;

    const uint32_t seed = 12345;
    const uint32_t width = 600;
    const uint32_t height = 400;

    // Temporary filenames for test output
    const char* initial_filename = "/tmp/test_regression_initial.png";
    const char* final_filename = "/tmp/test_regression_final.png";

    // Create simulation with same parameters as baseline
    void* p = platec_api_create(seed, width, height, 0.65, 60, 0.02, 1000000, 0.33, 2, 10);
    ASSERT_NE(p, nullptr) << "Failed to create simulation";

    // Save initial state
    save_image(p, initial_filename, width, height);

    // Run simulation to completion
    while (platec_api_is_finished(p) == 0) {
        platec_api_step(p);
    }

    // Save final state
    save_image(p, final_filename, width, height);

    // Compute checksums
    uint32_t initial_crc32 = compute_file_checksum(initial_filename);
    uint32_t final_crc32 = compute_file_checksum(final_filename);

    // Clean up
    platec_api_destroy(p);

    // Compare checksums
    EXPECT_EQ(initial_crc32, EXPECTED_INITIAL_CRC32)
        << "Initial image checksum does not match baseline.\n"
        << "Expected: 0x" << std::hex << EXPECTED_INITIAL_CRC32 << "\n"
        << "Got:      0x" << std::hex << initial_crc32 << "\n"
        << "This indicates the simulation initial state has changed.";

    EXPECT_EQ(final_crc32, EXPECTED_FINAL_CRC32)
        << "Final image checksum does not match baseline.\n"
        << "Expected: 0x" << std::hex << EXPECTED_FINAL_CRC32 << "\n"
        << "Got:      0x" << std::hex << final_crc32 << "\n"
        << "This indicates the simulation output has changed.";

    // Clean up test files
    std::remove(initial_filename);
    std::remove(final_filename);
}
