name: Workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  my_python_job:
    name: "Python"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - 2.7.18
#          - 3.4.10 broken?
          - 3.6.15
          - 3.8.20
          - 3.10.16
          - 3.11.11
          - 3.12.8

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update; sudo apt install build-essential libssl-dev zlib1g-dev \
          libbz2-dev libreadline-dev libsqlite3-dev curl git \
          libncursesw5-dev xz-utils tk-dev libxml2-dev libxmlsec1-dev libffi-dev liblzma-dev

      - name: Build Plate Tectonics
        run: |
          cmake . -G "Unix Makefiles"
          make -j2

      - name: Test Plate Tectonics
        run: |
          cd test
          make -j2
          ./test_plate_tectonics

      - name: Install python
        uses: gabrielfalcao/pyenv-action@v18
        with:
          default: "${{ matrix.python }}"
          command: pip install -U pip wheel setuptools twine # upgrade pip after installing python

      - name: Build
        run: |
          cd pybindings && python setup.py clean build sdist bdist bdist_wheel

      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: python-build-${{ matrix.python }}
          path: pybindings/dist/